# Generated by Django 5.2.4 on 2025-07-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('pattern_source', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('wips', 'WIPs'), ('finished', 'Finished'), ('frogged', 'Frogged'), ('graveyard', 'Graveyard')], default='planned', max_length=20)),
                ('hook_size', models.CharField(blank=True, choices=[('B-1', '2.25 mm'), ('C-2', '2.75 mm'), ('D-3', '3.25 mm'), ('E-4', '3.5 mm'), ('F-5', '3.75 mm'), ('G-6', '4.0 mm'), ('7', '4.5 mm'), ('H-8', '5.0 mm'), ('I-9', '5.5 mm'), ('J-10', '6.0 mm'), ('K-10.5', '6.5 mm'), ('L-11', '8.0 mm'), ('M-13', '9.0 mm'), ('N-15', '10.0 mm'), ('P-16', '11.5 mm'), ('Q', '15.75 mm'), ('S', '19.0 mm')], max_length=10, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extra_hard', 'Extra Hard')], max_length=20, null=True)),
                ('colors', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
