# Generated by Django 5.2.4 on 2025-07-31 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('user', 'date')},
        ),
    ]
